Ansible Cm Testing 29

diff --git a/.github/workflows/ansible.yml b/.github/workflows/ansible.yml
--- a/.github/workflows/ansible.yml
+++ b/.github/workflows/ansible.yml
@@ -31,6 +31,16 @@ jobs:
       - name: Setup Terraform
         uses: hashicorp/setup-terraform@v1
 
+      - name: Check for jq
+        run: |
+          if ! command -v jq &> /dev/null
+          then
+            echo "jq is not installed. Exiting."
+            exit 1
+          else
+            echo "jq is installed."
+          fi
+
       - name: Terraform Init
         run: terraform init
 
@@ -44,12 +54,29 @@ jobs:
         id: plan
         run: terraform plan -out=plan.tfplan
 
-      - name: Convert Terraform Output to JSON
-        run:  json_output=$(terraform output -json)
-        
-               
+      - name: Validate Terraform Output
+        run: |
+          terraform output -json > output.json
+          jq empty output.json
+          if [ $? -ne 0 ]; then
+            echo "Invalid JSON output from Terraform. Exiting."
+            exit 1
+          else
+            echo "Valid JSON output from Terraform."
+          fi
+
+      - name: Check for Changes
+        id: changes
+        run: |
+          CHANGES=$(terraform show -json plan.tfplan | jq -r '.resource_changes | length')
+          if [[ $CHANGES -eq 0 ]]; then
+            echo "No changes detected."
+            exit 0
+          fi
+          echo "::set-output name=changes::$CHANGES"
+
       - name: Terraform Apply
-        if: github.event_name == 'push' || (github.event.inputs.action == 'apply')
+        if: github.event_name == 'push' || (github.event.inputs.action == 'apply' && steps.changes.outputs.changes != '0')
         run: terraform apply -auto-approve plan.tfplan
 
       - name: Terraform Destroy
